Add Book repository
wolox-training/mq-java pull request #7
Opened 2020-02-14 13:25 UTC by tinoq-woloxer

## Summary
- Enables JPA repositories for the application
- Includes EntityScan annotation for the application
- Creates book repository extending JPA Repository

## Trello Card
- https://trello.com/c/stwv1sC2/15-crear-un-repositorio-de-books

## Dependencies
- https://github.com/wolox-training/mq-java/pull/1
- https://github.com/wolox-training/mq-java/pull/2
- https://github.com/wolox-training/mq-java/pull/3
- https://github.com/wolox-training/mq-java/pull/4

2020-02-14 18:45 UTC, rodrigofranc requested changes

2020-02-14 18:45 UTC, rodrigofranc commented on src/main/java/wolox/training/repositories/BookRepository.java
> +    Book findByTitle(String title);
Always return an Optional of the entity, and add `@NotNull` to param `title`

2020-02-17 14:38 UTC, rodrigofranc approved these changes

2020-02-17 14:48 UTC, leandrocostawolox approved these changes
Good job!

2020-02-17 14:52 UTC, merged