Create Book CRUD operations
wolox-training/mq-java pull request #8
Opened 2020-02-14 14:34 UTC by tinoq-woloxer

## Summary
- Fix base packages to scan for Entity, JPA and springboot when intializing the app
- Moved greeting endpoint to greeting controller
- Implement CRUD operations in Book controller
- Create BookIDMismatchException and BookNotFoundException to use in Book Controller CRUD.

## Trello Card
https://trello.com/c/krF0icI2/18-crear-las-operaciones-crud-de-book

## Dependencies
- https://github.com/wolox-training/mq-java/pull/6
- https://github.com/wolox-training/mq-java/pull/7

2020-02-17 17:54 UTC, rodrigofranc requested changes

2020-02-17 17:54 UTC, rodrigofranc commented on src/main/java/wolox/training/exceptions/BookIdMismatchException.java
> +
Add constructor here with message

2020-02-17 17:54 UTC, rodrigofranc commented on src/main/java/wolox/training/exceptions/BookNotFoundException.java
> +
Add constructor here with message

2020-02-17 17:54 UTC, rodrigofranc commented on src/main/java/wolox/training/controllers/BookController.java
> +    @GetMapping("/title/{bookTitle}")
`bookTitle` should be query param

2020-02-18 16:33 UTC, leandrocostawolox approved these changes

2020-02-19 13:59 UTC, closed without merging